folder: /media/aiteam/storage/AI_DATA/fire_smoke_dataset/eda/mAP/fire_person/input
no_animation: true #no animation is shown
no_plot: true #no plot is shown.
quiet: true #minimalistic console output
ignore: null ## ignore a list of classes
set_class_iou: null # set IoU for a specific class.